apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
  labels:
    name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
      - job_name: 'ml-workflow'
        static_configs:
          - targets: ['ml-workflow.default.svc.cluster.local:8080']
      - job_name: 'minio'
        metrics_path: '/minio/metrics/v3'
        static_configs:
          - targets: ['minio-service.default.svc.cluster.local:9000']
      
