apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: monitoring
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
    [INPUT]
        Name         tail
        Path         /var/log/containers/*.log
        Parser       docker
        Tag          kube.*
    [FILTER]
        Name         kubernetes
        Match        kube.*
        Merge_Log    On
    [OUTPUT]
        Name         es
        Match       *
        Host        elasticsearch.default.svc.cluster.local
        Port        9200
        Logstash_Format On
