apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-workflow
  labels:
    app: ml-workflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-workflow
  template:
    metadata:
      labels:
        app: ml-workflow
    spec:
      containers:
      - name: data-fetch
        image: data-fetch
        imagePullPolicy: Never
        ports:
          - containerPort: 8081
        # Remove or adjust probes if data-fetch doesn't serve HTTP
      - name: data-ingestion
        image: data-ingestion
        imagePullPolicy: Never
        ports:
          - containerPort: 8080   # Changed to 8080 to match Flask's binding
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
      - name: model-training
        image: model-training
        imagePullPolicy: Never
        ports:
          - containerPort: 8083
        env:
          - name: MINIO_URL
            value: "minio-service.default.svc.cluster.local:9000"  # Updated endpoint
        readinessProbe:
          httpGet:
            path: /ready
            port: 8083
          initialDelaySeconds: 20
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8083
          initialDelaySeconds: 30
          periodSeconds: 10
